### ISSUE TITLE
Missing Direct/Forwarded TCP IP Examples

### ISSUE THREAD

**Issue by edualm** [apple/swift-nio-ssh#54]
Hello,

I was playing around with the library, and while the client example is good and shows how to establish a simple SSH connection, I can't quite figure out how to configure a direct TCP connection. I was able to change the example to open a channel of `directTCPIP` type, but it seems to be ignoring the `originatorAddress`, which I am assuming would be a port on my computer (just like when I call `ssh -NL`) but I am probbaly wrong.

I probably am not being able to figure it out as I haven't tried Swift NIO before, but an example on those kinds of connections would be helpful to me and probably to many others. :)

Thanks in advance!

**Comment by Lukasa** [comment]
Hey @edualm thanks for filing this issue!

NIOSSH is substantially lower level than you might be expecting. In this instance, it's giving you the pieces of the wire protocol, but it isn't giving you the equivalent application logic to implement them as you're expecting. This is intended behaviour: we want you to be able to do _anything_ with a `directTCPIP` channel, not only to use it in the straight-line SSH forwarding mode where you actually create a listening port. This means when you create your `directTCPIP` channel, NIO does not start listening on any port for you. In fact, it does nothing at all beyond creating that channel in the SSH connection.

To create this example we'd need to flesh the code out a lot, in order to use things like a server bootstrap for the listening port. I've thrown together an extension to the example client in #55. This roughly shows how you would implement the traditional port forwarding code, by gluing together an inbound connection and an SSH channel.

**Comment by edualm** [comment]
Hey @Lukasa,

Thank you **so much** for taking some time out of your day doing this.

The example is all I could have asked for, and is more than enough for me to start hacking something.

Hope it benefits others and not just me!
